# Public keys corresponding to private keys that should be able to decrypt 
# secrets
keys:
  - &dev age1ez5jd5r7h90jqtkysmymac0twxvyugzhh3e2jdvzuqlhav5vsp0sgqrcsm
  - &nixpi age1jlz3uu4whj79k2fc0hrjhpkjzn02drpj7vkct9zcrx2cupht54tsfwz8dy

creation_rules:
  - path_regex: ./.*\.(yaml|json|env|ini|txt|sops)$
    key_groups:
      - age:
        - *dev
        - *nixpi