# Public keys corresponding to private keys that 
# should be able to decrypt secrets
keys:
  # My machine that I am using to develop these configs
  - &dev age1ez5jd5r7h90jqtkysmymac0twxvyugzhh3e2jdvzuqlhav5vsp0sgqrcsm

  # NixPi host public key so it can decrypt secrets I encrypt on my dev machine
  - &nixpi age1r7nnuznweq9dav8j66037mxcfwylekp9frcsem28u20573h0cu2sdnf680

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
        - *dev
        - *nixpi