# Public keys corresponding to private keys that should be able to decrypt 
# secrets
keys:
  - &dev age1ez5jd5r7h90jqtkysmymac0twxvyugzhh3e2jdvzuqlhav5vsp0sgqrcsm
  - &nixpi age1r7nnuznweq9dav8j66037mxcfwylekp9frcsem28u20573h0cu2sdnf680

creation_rules:
  - path_regex: secrets/.*\.(yaml|json|env|ini|txt|sops)$
    key_groups:
      - age:
        - *dev
        - *nixpi